### ISSUE TITLE
Greenscreen Bug Report

### ISSUE THREAD

**Issue by cosmoproductions** [isivisi/questionablemodules#54]
Module: Greenscreen
Plugin Version: 2.1.10
JSON: `{"id": 8998864862134520, "plugin": "questionablemodules", "model": "greenscreen", "version": "2.1.10", "params": [], "data": {"colorR": 0.015686275437474251, "colorG": 0.95686280727386475, "colorB": 0.015686275437474251, "text": "Green", "showText": true}}`
---------- Please describe your problem below: ----------

**Comment by cosmoproductions** [comment]
Hello!
This is a good idea for a simple, useful module.  Well done.
Could ctrl+e to disable the module be implemented? Currently it just grays out the module, but doesn't disable the functionality. i.e. it stays enabled rather than showing the normal Rack background.
Plugin version 2.1.10 running in VCV Rack Pro 2.4.1 on Windows 10.
Thank you!

**Comment by isivisi** [comment]
Oh yea that's a good idea,
 I've implemented it in this commit: https://github.com/isivisi/questionablemodules/commit/4fbc5ddcab1f814156d8e45c90a50230d3736ecc. 

It should be in the next release (2.1.11) but you can download it now with nightbin or manually here: https://github.com/isivisi/questionablemodules/releases/tag/Nightly
