### ISSUE TITLE
Greenscreen Bug Report

### ISSUE THREAD

**Issue by alefnull** [isivisi/questionablemodules#75]
Module: Greenscreen
Plugin Version: 2.1.13
Rack Version: 2.4.1-win-x64
JSON: `{"id": 2312771274604655, "plugin": "questionablemodules", "model": "greenscreen", "version": "2.1.13", "params": [], "leftModuleId": 5172919201887855, "rightModuleId": 6237346442742493, "data": {"colorR": 0.0910000279545784, "colorG": 0.094000421464443207, "colorB": 0.091000922024250031, "text": "null", "showText": true, "showInputs": true, "hasShadow": false, "drawRack": false, "boxShadowX": 10.099952697753906, "boxShadowY": 10.000001907348633, "boxShadowColor": {"r": 0.59000009298324585, "g": 0.59100079536437988, "b": 0.59000003337860107, "name": ""}}}`
---------- Please describe your problem below: ----------

i've been using Greenscreen for several days, just leaving it in my default patch set to an almost black background and a medium-gray'ish box shadow, with the rack rails turned off. and while playing around with all of the settings a bit more just now, i realized i'm unable to toggle off the box shadows now that they're on. i can change their color just fine, but toggling the context menu item, while updating the menu item display to reflect the toggled state, is not actually toggling the shadows at all. (note, this is not a problem for me, since i like the box shadows a lot lol, but figured i'd raise the issue in case nobody else had.)

**Comment by isivisi** [comment]
You can quickly disable the box shadow by double clicking both the sliders, resetting them to 0. But do you mean you'd want a way to toggle the box shadow visuals while preserving the state?

Also what do you mean by this?
> "but toggling the context menu item, while updating the menu item display to reflect the toggled state, is not actually toggling the shadows at all."

Im confused at what you mean when you "toggle" a slider element. Or are you referring to the "toggle shadow" option that toggles the default vcv shadow effect for the module? 

If that's the case I might update that name and the docs to make that easier to differentiate XD

**Comment by alefnull** [comment]
> You can quickly disable the box shadow by double clicking both the sliders, resetting them to 0. But do you mean you'd want a way to toggle the box shadow visuals while preserving the state?
> 
> Also what do you mean by this?
> 
> > "but toggling the context menu item, while updating the menu item display to reflect the toggled state, is not actually toggling the shadows at all."
> 
> Im confused at what you mean when you "toggle" a slider element. Or are you referring to the "toggle shadow" option that toggles the default vcv shadow effect for the module?
> 
> If that's the case I might update that name and the docs to make that easier to differentiate XD

yeah, i assumed that the menu option "Toggle Shadow" was referring to the box shadow drawn by Greenscreen. my mistake.

**Comment by isivisi** [comment]
No worries, it does seem like they would be related, that will be changed soon :)
